# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               Jay archive
tagline:             ''
description:         ''
url:                 http://mnpk.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jay
  url:               https://mnpk.github.io/
  email:             mnncat@gmail.com

# Custom vars
version:             1.0.0

# gem required
plugins:
  - jekyll-feed
  - jekyll-paginate
